name: Publish Anamnesis

on:
  workflow_dispatch:

jobs:

#  changelog:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    
#    - name: Get version date
#      uses: 1466587594/get-current-time@v2
#      id: version-date
#      with:
#        format: YYYY-MM-DD
#        
#    - name: Create Release draft
#      uses: ncipollo/release-action@v1
#      with:
#        allowUpdates: true
#        name: ${{ steps.version-date.outputs.formattedTime }} (Beta)
#        tag: v${{ steps.version-date.outputs.formattedTime }}-beta
#        body: 'changelog generating...'
#        draft: true
#        token: ${{ secrets.GITHUB_TOKEN }}
#        
#    - name: Checkout
#      uses: actions/checkout@v2
#      with:
#        fetch-depth: 0
#
#    - name: Changelog
#      id: Changelog
#      uses: mikepenz/release-changelog-builder-action@v2.4.1
#      with:
#        #configuration: 'changelogConfig.json'
#        toTag: v${{ steps.version-date.outputs.formattedTime }}-beta
#        commitMode: true
#        failOnError: true
#        token: ${{ secrets.GITHUB_TOKEN }}
#
#    - name: Upload Release
#      uses: ncipollo/release-action@v1
#      with:
#        allowUpdates: true
#        name: ${{ steps.version-date.outputs.formattedTime }} (Beta)
#        tag: v${{ steps.version-date.outputs.formattedTime }}-beta
#        body: ${{ steps.Changelog.outputs.changelog }}
#        draft: true
#        token: ${{ secrets.GITHUB_TOKEN }}

  build:

    runs-on: windows-latest

    steps:
    
    - name: Get version date
      uses: 1466587594/get-current-time@v2
      id: version-date
      with:
        format: YYYY-MM-DD
        
    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: build-time
      with:
        format: YYYY, MM, DD, HH, mm, ss
      
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Checkout Submodules
      uses: snickerbockers/submodules-init@v4
      
    - name: Write Version file
      uses: visiosto/replace-value@v1.0.0
      with:
        file: './Anamnesis/VersionInfo.cs'
        replaced: '2000, 01, 01, 00, 00, 00'
        value: ${{ steps.build-time.outputs.formattedTime }}

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 5.0.x
   
    - name: Deploy Anamnesis
      run: dotnet publish Anamnesis/Anamnesis.csproj /p:PublishProfile=".\Anamnesis\Properties\PublishProfiles\FolderProfile.pubxml"
      
    - name: Deploy Update Extractor
      run: dotnet publish UpdateExtractor/UpdateExtractor.csproj /p:PublishProfile=".\UpdateExtractor\Properties\PublishProfiles\FolderProfile.pubxml"

    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.0
      with:
        filename: '../${{ steps.version-date.outputs.formattedTime }}-pre-alpha.zip'
        directory: './publish/'
        exclusions: '*.pdb* *.xml*'
        
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "${{ steps.version-date.outputs.formattedTime }}-pre-alpha.zip"
        name: ${{ steps.version-date.outputs.formattedTime }} (Pre-Alpha)
        tag: v${{ steps.version-date.outputs.formattedTime }}-Pre-Alpha
        #body: ${{ steps.Changelog.outputs.changelog }}
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
